### ISSUE TITLE
API pagination limit parameter returns incorrect size

### ISSUE THREAD

**Issue by jamesfzhang** [soundcloud/soundcloud-ruby#49]
I'm noticing a pagination issue with the "limit" parameter.

When limit is set to 68 or below, the collection returned respects the size constraint. When it is set to n where n >= 69, the collection returned is of size n - 1.

For instance, this user has over 8,000 followers.

```ruby
 > response = client.get("/users/#{soundcloud_id}/followers", limit: 68);response.collection.length
=> 68 
 > response = client.get("/users/#{soundcloud_id}/followers", limit: 69);response.collection.length
=> 68
 > response = client.get("/users/#{soundcloud_id}/followers", limit: 70);response.collection.length
=> 69
```

**Comment by alonpeer** [comment]
Hi @jamesfzhang. The `limit` parameter actually means "max size". Because of the complexity of our systems, we cannot guarantee an exact number of items returned for each request.
Please use the `next_href` field to field if there are more items to fetch, instead of relying on the precise size of the `collection` array.
Does this make sense?
