### ISSUE TITLE
Update hashie dependency to 3.x

### ISSUE THREAD

**Issue by chrismaddocks** [soundcloud/soundcloud-ruby#57]
The gemspec has a version specifier of `'~> 2.0'` for hashie. Any reason not to update this to `'~> 3.0'`, or support both? We are starting to run into dependency conflicts with other gems.

It appears to work fine locally, but I'm not sure if there is a reason for pinning it to 2.x.

**Comment by grobie** [comment]
Tbh. I don't even see a reason to wrap the responses in a Hashie::Mash object before returning it to the caller, if that's required it could be done by the caller itself, but I don't want to make such a potentially disruptive interface change now. As the library itself doesn't use the Mash object on its own, it doesn't have any requirements of the used hashie gem version. Therefore I simply removed the version requirement from the gemspec. Use whatever makes sense in your project.

Fixed with the latest release [v0.3.4](https://rubygems.org/gems/soundcloud/versions/0.3.4).
